### PR TITLE
german translation / mustache notification fixing

### PR DESCRIPTION
**Pull request by emphasize**
A quick adjustment to be on a level with the english template which i think is canon. Hopefully, since i don't know he code :P
The only deviation was to get rid of the "" from "{{dev_name}}" which was not breaking but unnecessary.

### CODE REVIEW

**Comment by emphasize** [comment]
To add, i found nothing relevant to translate. Maybe i missed somethin, let me know

**Comment by Tony763** [comment]
Hi @emphasize, sorry I did forget to mention which branch would be translated. It's turn_on_all-group-squash. Thanks

**Comment by gador** [comment]
Hi @emphasize,
may I ask, why you added the double "{{" bracket? AFAIK it is unnecessary..

**Comment by Tony763** [comment]
"{{" are already included in some languages and should be removed. I will check it in final clean up.

**Comment by emphasize** [comment]
The double brackets stem from the english template of the default branch (which was 20.02). Tony forgot to mention that "turn_on_all-group-squash" branch is the one to commit to 😛 

In that case {{ is not only unnecessary, it's breaking

**Comment by Tony763** [comment]
"{{" removed from all languages.

**Pull request closed without merging**
