### PR TITLE
remove whitespace

### PR DESCRIPTION
**Pull request by pfefferle**
as requested :)

### CODE REVIEW

**Comment by pfefferle** [comment]
seems not running at all... maybe because it is a PR to a branch?

**Comment by Tony763** [comment]
Perfect, stage one works.

**Comment by Tony763** [comment]
Stage two too. :smile: 

Let's see if overall test will be successful.

**Comment by Tony763** [comment]
@pfefferle Could you try to fix the linter error now with new commit to this PR? No need to fix conflicted `build.yaml`

**Comment by pfefferle** [comment]
done

**Comment by pfefferle** [comment]
nice! 😍

**Comment by pfefferle** [comment]
But this runs all tests only the label? Is it possible to add the label requirement only for the geh-pages stuff?

**Comment by Tony763** [comment]
Check new PR [#87](https://github.com/MycroftAI/skill-homeassistant/pull/87). Workflow is run only when maintainer check code and add label. I can't divide checks and upload from actual run as I would not have outcome from them and  I do not want to run the workflow two times. Every contributor can run its own GA so code can be checked before sending PR. With opened PR, when You make a new commit, it still runs check in Your fork. So You know You did it right.

**Comment by Tony763** [comment]
Hi @pfefferle, could you please create ideally another two PR to actual [github-action-pr-fix](https://github.com/Tony763/skill-homeassistant/tree/feature/github-action-pr-fix) branch? One with some small change into `.github/workflow/build.yml` and second to somewhere in code?

**Comment by pfefferle** [comment]
sure!

**Pull request closed without merging**
